### ISSUE TITLE
Check reproducibility of the physics packages

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#239]
## Description
Provide a report on the physics packages what do not pass reproducibility test (utest)

### To Reproduce:
Run utest to check the operational requirement such as reproducibility

## Output
A report about the reproducibility status for all the current RT tests will be provided.

**Comment by climbfuji** [comment]
Closed via https://github.com/ufs-community/ufs-weather-model/pull/325.

**Comment by junwang-noaa** [comment]
Dom, please leave this issue open as the original plan is to check the reproducibility of all the available physics packages including fv3_ccpp_gfs_v16beta_RRTMGP, HAFS_v0_hwrf_thompson, FV3_GFS_2017_gfdlmp_noahmp etc. So far I think: FV3_GFS_2017, FV3_GFS_v15p2,FV3_GFS_v16beta, FV3_GSD_v0, GFS_v15_thompson have reproducibility. Please let me know if I missed other packages.

**Comment by climbfuji** [comment]
Sorry. I had listed it as an issue addressed by the PR, and nobody objected. Thanks for reopening it.

**Comment by arunchawla-NOAA** [comment]
@junwang-noaa and @climbfuji where are we with this issue ? I see issues open for restart reproducibility in regional physics packages

**Comment by junwang-noaa** [comment]
So far following physics packages have been checked:
1) GFSv16, GFS_v15p2, GFS_v15p2_coupled, and FV3_GFS_v16_coupled. reproducible for threading/decomposition/restart 
2) GFSv16_RRTMGP, threading issue is fixed. no results yet for decomposition and restart
3) GFS_v15_thompson_mynn, threading and decomposition issues are fixed, need final solution for restart.

**Comment by climbfuji** [comment]
> So far following physics packages have been checked:
> 
> 1. GFSv16, GFS_v15p2, GFS_v15p2_coupled, and FV3_GFS_v16_coupled. reproducible for threading/decomposition/restart
> 2. GFSv16_RRTMGP, threading issue is fixed. no results yet for decomposition and restart
> 3. GFS_v15_thompson_mynn, threading and decomposition issues are fixed, need final solution for restart.

As for 3, this is not a problem of the physics suite, but because it is a regional run, correct?

**Comment by junwang-noaa** [comment]
Yes.

**Comment by arunchawla-NOAA** [comment]
@junwang-noaa @climbfuji and @grantfirl should this issue still be open ? are there physics packages in ccpp that are not restart reproducible ?

**Comment by climbfuji** [comment]
> @junwang-noaa @climbfuji and @grantfirl should this issue still be open ? are there physics packages in ccpp that are not restart reproducible ?

Very likely there are, since it's not tested by default for every new physics package or option being added. There is the opnReqTest that is supposed to be used each time, but for many legacy packages this hasn't been run.

**Comment by arunchawla-NOAA** [comment]
@climbfuji @yangfanglin @ChunxiZhang-NOAA should legacy SDFs be removed from the UFS host model side ? We should only be keeping the SDFs that we are regularly testing in the regression test suite.

**Comment by climbfuji** [comment]
@arunchawla-NOAA I declared defeat over that question a while ago.

**Comment by junwang-noaa** [comment]
@ChunxiZhang-NOAA @yangfanglin @grantfirl Since Chunxi is cleaning up the CCPP suite files, I suggest to close this issue and open a new one after the clean up. What do you think?

**Comment by ChunxiZhang-NOAA** [comment]
@junwang-noaa I only cleaned the suites related to RRTMGP for PR#1196. I can created another PR that simply moving those SDFs not used by RTs to a legacy directory. Since the PR doesn't change baselines, it will be an easy one.

**Comment by DeniseWorthen** [comment]
Can we create an issue for moving the untested SDFs to an ``untested`` subdirectory and then close this one?

**Comment by arunchawla-NOAA** [comment]
I am fine with that solution.

**Comment by DeniseWorthen** [comment]
@ChunxiZhang-NOAA Can you create an issue for this?

**Comment by ChunxiZhang-NOAA** [comment]
@DeniseWorthen Sue, I will create an issue.

**Comment by ChunxiZhang-NOAA** [comment]
@DeniseWorthen Please check this [Issue](https://github.com/NOAA-EMC/fv3atm/issues/510) I created a long time ago but updated today.

**Comment by DeniseWorthen** [comment]
Thanks @ChunxiZhang-NOAA. I'm going to close this issue then.
