### ISSUE TITLE
Zonally asymmetric structures in TOA downward shortwave?

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-weather-model#2785]
We've been looking at the TOA radiation balance in the C96mx100 SFS_baseline runs and our own C192mx025 runs and have found zonally asymmetric patterns in the downward shortwave field that we can't explain. 

C96mx100:

<img width="612" alt="Image" src="https://github.com/user-attachments/assets/d4f1c535-e8a0-4fed-9c35-706efdbca088" />

It's not obviously related to the cube sphere grid, and it changes with month. These are taken from monthly mean values, which were in turn calculated from daily mean output, so there shouldn't be any kind of imprinting of the sun position. The magnitudes of the anomalies are ~30x what I saw in the same calculation for some random CMIP6 data I compared it to. 

Very curious to know if people have seen these patterns elsewhere and if they have a known origin.

**Comment by benjamin-cash** [comment]
@lisa-bengtsson, @ligiabernardet - any insights into what might be happening here?

**Comment by lisa-bengtsson** [comment]
Hm.. very peculiar. I'm reaching a bit here - but could it be large scale patterns from SPPT that becomes visible when doing this type of averaging? Do you see the same in e.g. member 0 that doesn't have stochastic physics?

**Comment by benjamin-cash** [comment]
It does appear to be present in mem000 as well. This is from a single day grabbed at random so the pattern is not the same, but is still clearly present. 

<img width="1150" alt="Image" src="https://github.com/user-attachments/assets/7e84add2-ac31-4a81-8e8d-e20d316cd205" />

Accidentally chopped the scale in the screenshot, but the range is (-0.4,0.4) W/m**2.

**Comment by lisa-bengtsson** [comment]
In this last plot, the streaks look to be aligned with the diurnal cycle and propagating westward which suggest an artifact related to the radiation parameterization. Such artifacts could arise when shortwave radiation is updated too infrequently, causing it to lag behind the actual solar forcing. This can lead to systematic phase errors that propagate westward with the sun. A sensitivity experiment could be to call radiation every time-step, but that would be too expensive in practice... @dustinswales may have thoughts on this?

**Comment by benjamin-cash** [comment]
@pjpegion - just tagging you into the discussion. @lisa-bengtsson, another oddity that has emerged is there is an offset in the zonal mean of the downward shortwave between my C192mx025 runs and the baseline C96mx100 runs. The plot below is for January - the difference is strongest in Nov and Jan. I'm a little less confident in this result, since it is monthly data and could be a bug in the monthly averaging. But the zonally asymmetric pattern turned out to be robust so I'm including it - I'd like to verify this with the daily output fields. 

<img width="995" alt="Image" src="https://github.com/user-attachments/assets/fe65340f-65cc-4e27-b724-92e8609f318a" />

**Comment by yangfanglin** [comment]
I am yet to find the time to fully understand the issue Ben described here.  But it may or may not be related to this PR https://github.com/ufs-community/ccpp-physics/pull/262.    SW is called only once per hour in the model.  The actual SW used at each physics time step is scaled by cos(zenth_angle).  There are variations in accumulating flux at each timestep and computing time averaged SW fluxes.  For coarse resolution model the issue becomes more tricky at low sun angles.  We once noticed in the past even grib packing (precision) can make a difference.

**Comment by benjamin-cash** [comment]
Hi @yangfanglin - The short version is just that there is what looks to be some kind of solar imprinting in the 24-hour average downward shortwave at the top of the atmosphere, which doesn't seem like it should be there. The magnitude is much larger (30x) than the random CMIP6 data I compared it to. I'd love to take a look at the RT data from that PR and see if these anomalies are still present or if it resolves them.

**Comment by benjamin-cash** [comment]
I'd also like to compare some daily SFS_baseline TOA downward shortwave to my C192 runs to see if this systematic reduction in C192 is real or if it's because of something wrong in the monthly averaging.

**Comment by ligiabernardet** [comment]
@ShanSunNOAA  Tagging you in case you have additional insight

**Comment by benjamin-cash** [comment]
If someone more familiar with how to pull in the modifications described in the PR can make even a 48 hour run I'd be happy to analyze it and see if this effect is still present. I'm just not sure what the status of that code is and what would be required to run it correctly.

**Comment by dustinswales** [comment]
@benjamin-cash You cloud clone a fresh copy of the UWM and run a SFS based RT pretty easily, I'm just not sure which RT you should start with. @lisa-bengtsson might know which RT is closest to the experiment(s) you are running above.

`> git clone --recursive https://github.com/ufs-community/ufs-weather-model.git`
`> cd  ufs-weather-model/tests`

Modify rt.conf. For example, [remove all lines except 50-51](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.conf#L50).

`> ./rt.sh -a XYZ -k`

Also, the RTs are usually short integrations, so you _might_ need to go into the `run_dir` and modify `model_configure` to run the forecast for 48 hours.

**Comment by lisa-bengtsson** [comment]
@dustinswales I believe what Ben is asking is what is needed to run the model with the changes proposed in PR https://github.com/ufs-community/ccpp-physics/pull/262 to see if that alleviates the patterns he's seeing.

**Comment by benjamin-cash** [comment]
Hi @dustinswales - Yes, exactly what @lisa-bengtsson said, although the refresher on the regression tests is also welcome. I don't really follow from the discussion in the other PR what branches I would need to check out to run this.

As another data point, I dug up some P8 data that I still have locally and this same kind of pattern is clearly visible there as well.

**Comment by lisa-bengtsson** [comment]
@benjamin-cash 

You could try:
git clone https://github.com/ufs-community/ufs-weather-model.git
cd ufs-weather-model

git fetch origin pull/2660/head:pr2660
git checkout pr2660

cd ufs-weather-model
git submodule update --init --recursive

Then run a SFS regression test as Dustin indicated above. 

(There are PR's to ufs-weather-model, FV3 and CCPP, the top level is ufs-weather model here:
https://github.com/ufs-community/ufs-weather-model/pull/2660)

**Comment by benjamin-cash** [comment]
Thanks @lisa-bengtsson, I'll give that a shot. On a related note, do you have any ideas as to why the C192 runs would have systematically lower toa downward shortwave than C96 that I show above? I checked just now and it doesn't appear to be coming from the regridding I used.

**Comment by lisa-bengtsson** [comment]
@benjamin-cash Kate (@XiaqiongZhou-NOAA ) ran a clean C192 vs C96 experiment based on SFS_betav0.1. She has put the monthly mean fields and their differences on this website: https://www.emc.ncep.noaa.gov/gc_wmb/xzhou//SFS/base_c192/

I noted that the DSWRFTOA field looks strange, just like stripes. So I wonder if there is an issue with the UPP for TOA shortwave diagnostics? Regarding the difference between C192 and C96 - there is a pretty large impact on clouds, you can click through the fields.

**Comment by dustinswales** [comment]
@benjamin-cash Sorry for the confusion, for some reason I thought that fix was merged in. My apologies.
What @lisa-bengtsson listed will get you those changes in for testing.

**Comment by benjamin-cash** [comment]
No worries. :) I was able to run it, but unfortunately the output wasn't especially useful. The netcdf files were only written at 000, 021, and 024, and while the grib files were written every 3h from 00 to 24 the files appear to be identical until 021. Is there a regression test that provides daily average values? I can try hacking the configure files but it's been a while and I'm likely to miss something.

**Comment by dustinswales** [comment]
I think all that you need to do to extend the forecast time and output frequency is to modify the `model_configure` file in the run_dir. So something like this: 
`- nhours_fcst:             24`
`+ nhours_fcst:             48`
`- output_fh:               0 21 24`
`+ output_fh:               1 -1`

**Comment by benjamin-cash** [comment]
Ok, assuming that I picked up the branch correctly the issue is still present. The output from my run is on Hercules:
/work2/noaa/stmp/cash/stmp/cash/FV3_RT/rt_1689715/cpld_control_sfs_intel

and my code is here:
/work/noaa/nems/cash/ufs-weather-model

**Comment by lisa-bengtsson** [comment]
@benjamin-cash 

Xiao-Wei Quan here at PSL did 10 year average plots from SFS runs, and compared with ERA5. E.g. ERA5-CERES obs and SFS - CERES obs, and a peculiar di-pole pattern is visible also in the ERA5-CERES comparison, but different frequency from SFS. Maybe an artifact from radiation being called hourly? ...Not sure.

https://docs.google.com/presentation/d/1vIYwQO_kSVRSQHlCKsZK4QkGgwwvsBYG_eNXtp4Afek/edit?slide=id.p#slide=id.p

**Comment by benjamin-cash** [comment]
> [@benjamin-cash](https://github.com/benjamin-cash)
> 
> Xiao-Wei Quan here at PSL did 10 year average plots from SFS runs, and compared with ERA5. E.g. ERA5-CERES obs and SFS - CERES obs, and a peculiar di-pole pattern is visible also in the ERA5-CERES comparison, but different frequency from SFS. Maybe an artifact from radiation being called hourly? ...Not sure.
> 
> https://docs.google.com/presentation/d/1vIYwQO_kSVRSQHlCKsZK4QkGgwwvsBYG_eNXtp4Afek/edit?slide=id.p#slide=id.p

Request sent. :)

**Comment by benjamin-cash** [comment]
Thanks @lisa-bengtsson! This is a little different from what I was seeing, which is purely a model-to-model comparison. That bias in ERA5 is kind of wild-looking!

**Comment by DeniseWorthen** [comment]
I'm definitely outside my wheelhouse here, but those figures remind me of the Figure 3 [here](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL063239), which I happened upon because of Issue #1767

**Comment by lisa-bengtsson** [comment]
> I'm definitely outside my wheelhouse here, but those figures remind me of the Figure 3 [here](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL063239), which I happened upon because of Issue [#1767](https://github.com/ufs-community/ufs-weather-model/issues/1767)

Very interesting Denise, is the final PR to solve the issue 1767 the one from Grant Firl here: https://github.com/ufs-community/ufs-weather-model/pull/2660 ?

**Comment by DeniseWorthen** [comment]
I don't believe the PR from Grant is expected to fix the coupling SW fields, because those are instantaneous values, not time-averaged diagnostic fields, but I will test and see if there is an impact.

**Comment by benjamin-cash** [comment]
@DeniseWorthen - Did anything interesting come out of this test?

**Comment by DeniseWorthen** [comment]
I only verified that the coupled fields are not modified by this fix.

**Comment by gspetro-NOAA** [comment]
Has this issue been resolved? If not, is anyone still working on it?

**Comment by benjamin-cash** [comment]
I have not looked at this recently, but I took a quick glance at the SFS Beta 0.1 data I have access to and there is still something weird going on. This looks much more like a grid imprint problem though. 

<img width="1347" height="451" alt="Image" src="https://github.com/user-attachments/assets/d66931e9-201e-49bd-b1a8-9772441205bb" />
